
{$define TopLinear}
{$i LCDLinear.inc}
{$undef TopLinear}

{$define BotLinear}
{$i LCDLinear.inc}
{$undef BotLinear}

{$define TopMapped}
{$i LCDMapped.inc}
{$undef TopMapped}

{$define BotMapLED}
{$i LCDMapped.inc}
{$undef BotMapLED}

{$define ColVertLine}

{$define TopMapped}
{$i LCDMapped.inc}
{$undef TopMapped}

{$define BotMapLED}
{$i LCDMapped.inc}
{$undef BotMapLED}

{$undef ColVertLine}

//kdl