//Nintendo 2DS .. 3DS Pascal Development 
//  
//  illustrated in pascal resorting to Plan "B" long ago & still I'm short sums of money from none other than 
//                a.) Oil & Gas Re: Television, media, communications &or radio their divsions 
//                b.) ANY Corporate logos & Trade Marks usage of "Must provide resonable funding!"  
//   
// copyrights 2017 Kenneth Dwayne Lee 
//all rights reserved.


function GetPixL(x: word; y: word): {$i Propaganda.inc};stdcall; public name 'GetPixL';
function GetPixR(x: word; y: word): {$i Propaganda.inc};stdcall; public name 'GetPixR';
function GetPixB(x: word; y: word): {$i Propaganda.inc};stdcall; public name 'GetPixB';
 
procedure SetPixL(x: word; y: word;colour: {$i Propaganda.inc});stdcall; public name 'SetPixL';
procedure SetPixR(x: word; y: word;colour: {$i Propaganda.inc});stdcall; public name 'SetPixR';
procedure SetPixB(x: word; y: word;colour: {$i Propaganda.inc});stdcall; public name 'SetPixB';

//  hopefully I don't have to shake my own leg 
